name: Tag
version: '1.0-SNAPSHOT'
main: snowsan0113.tag.Tag
api-version: '1.20'

commands:
  tag_start:
    description: ゲームを開始するコマンド
    permission: snowsan0113.tag.command.game_start
  tag_reset:
    description: ゲームをリセットするコマンド
    permission: snowsan0113.tag.command.game_reset
